# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "luongvudinhduy2003@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "AWS System Manager"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> Luong Vu Dinh Duy"
identifier = "Luong Vu Dinh Duy FB"
url = "https://www.facebook.com/luong.duy.1207/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> DuyNe07"
identifier = "github DuyNe07"
url = "https://github.com/DuyNe07"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Luong Vu Dinh Duy"
identifier = "Luong Vu Dinh Duy LinkedIn"
url = "https://www.linkedin.com/in/duy-ne/"
weight = 20

[Languages.vi]
title = "AWS System Manager"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> Luong Vu Dinh Duy"
identifier = "Luong Vu Dinh Duy FB"
url = "https://www.facebook.com/luong.duy.1207/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> DuyNe07"
identifier = "github DuyNe07"
url = "https://github.com/DuyNe07"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Luong Vu Dinh Duy"
identifier = "Luong Vu Dinh Duy LinkedIn"
url = "https://www.linkedin.com/in/duy-ne/"
weight = 20